"use client";
import Image from "next/image";
import { motion } from "framer-motion";
import { Reveal } from "@/components/interactive/InteractionLayer";
const partners = ["ac-removebg-preview.png","bb-removebg-preview.png","cda-removebg-preview.png","coruggated-removebg-preview.png","equity-removebg-preview.png","gil-removebg-preview.png","hfc-removebg-preview.png","kpa-removebg-preview.png","kwft-removebg-preview.png","little-removebg-preview.png","mary-removebg-preview.png","mombasa_cement-removebg-preview.png","synergy-removebg-preview.png","transpares-removebg-preview.png"];
export default function Partners() {
 const logos=[...partners,...partners];
 return <section id="partners" className="overflow-hidden border-y border-border/60 bg-secondary/20 py-20 sm:py-24"><div className="container mx-auto px-5 sm:px-8 lg:px-10"><Reveal className="mb-12 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.32em] text-accent">Client relationships</p><h2 className="font-headline text-3xl font-bold tracking-tight text-primary sm:text-5xl">Trusted by leading organizations.</h2></div><p className="max-w-md text-sm leading-6 text-muted-foreground">We are honored to serve distinguished clients across diverse industries.</p></Reveal></div><div className="relative overflow-hidden [mask-image:linear-gradient(to_right,transparent,black_10%,black_90%,transparent)]"><motion.div className="flex w-max items-center" animate={{ x: ["0%", "-50%"] }} transition={{ duration: 42, repeat: Infinity, ease: "linear" }} whileHover={{ animationPlayState: "paused" }}>{logos.map((name,index)=><div key={`${name}-${index}`} className="flex h-24 w-[180px] shrink-0 items-center justify-center px-7 opacity-50 grayscale transition-all duration-500 hover:opacity-100 hover:grayscale-0 md:w-[220px]"><Image src={`/images/icons/${name}`} alt={name.replace(/-removebg-preview\.png$/,'').replace(/_/g,' ')} width={180} height={80} className="max-h-16 object-contain"/></div>)}</motion.div></div></section>;
}
